name: Build macOS Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install PyInstaller
      run: |
        pip install pyinstaller
        
    - name: Build macOS application with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "量化回测系统" --icon=NONE Qt_main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-application
        path: dist/